{
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at https://mozilla.org/MPL/2.0/
 *
 * Copyright (C) 2026, Peter Johnson (gravatar.com/delphidabbler).
 *
 * Routines to check for and resolve symlinks on both Linux and Windows.
}


unit USymlinks;

// NOTE:  This unit was adapted from code generated by ChatGPT, with errors
//        corrected.

interface

///  <summary>Checks if a file is a symlink.</summary>
///  <param name="AFileName">[in] Name of file to be checked.</param>
///  <returns><c>Boolean</c>. <c>True</c> if <c>AFileName</c> is a symlink or
///  <c>False</c> otherwise.</returns>
///  <exception><c>EApplication</c> is raised if <c>AFileName</c>'s attributes
///  can't be read.</exception>
function IsSymlink(const AFileName: string): Boolean;

///  <summary>Calculates and returns the name of the file pointed to by a
///  symlink.</summary>
///  <param name="ALinkName">[in] Name of the symlink file.</param>
///  <returns><c>string</c>. The name of the file referenced by the symlink.
///  </returns>
///  <exception><c>EApplication</c> is raised if an error occurs while
///  dereferencing the symlink.</exception>
///  <remarks><c>ALinkName</c> is expected to be a valid symlink file.</remarks>
function ResolveSymlink(const ALinkName: string): string;

implementation

uses
  System.SysUtils
  {$IF Defined(MSWINDOWS)}
  , Winapi.Windows
  {$ENDIF}
  {$IF Defined(LINUX)}
  , Posix.SysTypes
  , Posix.SysStat
  , Posix.Unistd
  , Posix.Errno
  , System.Character
  {$ENDIF}
  , UAppException
  ;

const
  MaxSupportedPathLen =
    {$IF Defined(MSWINDOWS)}
    32768
    {$ENDIF}
    {$IF Defined(LINUX)}
    4096
    {$ENDIF}
    ;

procedure RaiseFileAccessError(const AFileName: string);
resourcestring
  sError = 'Can''t access file "%s"';
begin
  raise EApplication.Create(
    sError, [AFileName], EApplication.ErrCantReadFileAttrs
  ) at ReturnAddress;
end;

procedure RaiseSymlinkParseError(const AFileName: string);
resourcestring
  sError = 'Can''t resolve symlink "%s"';
begin
  raise EApplication.Create(
    sError, [AFileName], EApplication.ErrCantResolveSymlink
  ) at ReturnAddress;
end;

function IsSymlink(const AFileName: string): Boolean;
{$IF Defined(MSWINDOWS)}
const
  // Reparse tag values from WinNT.h
  IO_REPARSE_TAG_SYMLINK      = $A000000C;
  IO_REPARSE_TAG_MOUNT_POINT  = $A0000003;
type
  TReparseGuidDataBuffer = record
    ReparseTag: DWORD;
    ReparseDataLength: Word;
    Reserved: Word;
    DataBuffer: array[0..16383] of Byte;
  end;
begin
  // Quick reject for non-reparse-point files
  var Attr: DWORD := GetFileAttributesW(PWideChar(AFileName));

  if Attr = INVALID_FILE_ATTRIBUTES then
    RaiseFileAccessError(AFileName);

  if (Attr and FILE_ATTRIBUTE_REPARSE_POINT) = 0 then
    Exit(False);

  {$WARN SYMBOL_PLATFORM OFF}
  var FileHandle := CreateFileW(
    PWideChar(AFileName),
    0,
    FILE_SHARE_READ or FILE_SHARE_WRITE or FILE_SHARE_DELETE,
    nil,
    OPEN_EXISTING,
    FILE_FLAG_OPEN_REPARSE_POINT or FILE_FLAG_BACKUP_SEMANTICS,
    0
  );
  {$WARN SYMBOL_PLATFORM ON}

  if FileHandle = INVALID_HANDLE_VALUE then
    RaiseFileAccessError(AFileName);

  try
    var ReparseBuffer: TReparseGuidDataBuffer;
    var BytesReturned: DWORD;
    if not DeviceIoControl(
      FileHandle,
      FSCTL_GET_REPARSE_POINT,
      nil,
      0,
      @ReparseBuffer,
      SizeOf(ReparseBuffer),
      BytesReturned,
      nil
    ) then
      RaiseFileAccessError(AFileName);

    // TRUE only for actual symbolic links
    Result := ReparseBuffer.ReparseTag = IO_REPARSE_TAG_SYMLINK;

  finally
    CloseHandle(FileHandle);
  end;
end;
{$ENDIF}
{$IF Defined(LINUX)}
begin
  var Utf8FileName: UTF8String := UTF8Encode(AFileName);
  var StatBuf: _stat;
  if lstat(PAnsiChar(Utf8FileName), StatBuf) <> 0 then
    RaiseFileAccessError(AFileName);
  Result := S_ISLNK(StatBuf.st_mode);
end;
{$ENDIF}

function ResolveSymlink(const ALinkName: string): string;
begin
  {$IF Defined(MSWINDOWS)}
  var FileHandle: THandle := CreateFileW(
    PWideChar(ALinkName),
    0,
    FILE_SHARE_READ or FILE_SHARE_WRITE or FILE_SHARE_DELETE,
    nil,
    OPEN_EXISTING,
    FILE_FLAG_BACKUP_SEMANTICS,
    0
  );

  if FileHandle = INVALID_HANDLE_VALUE then
    RaiseSymlinkParseError(ALinkName);

  var Buffer: array[0..Pred(MaxSupportedPathLen)] of WideChar;
  try
    {$WARN SYMBOL_PLATFORM OFF}
    var Len: DWORD := GetFinalPathNameByHandleW(
      FileHandle,
      Buffer,
      Length(Buffer),
      FILE_NAME_NORMALIZED
    );
    {$WARN SYMBOL_PLATFORM ON}
    if Len = 0 then
      RaiseSymlinkParseError(ALinkName);
    Result := Buffer;

    // Remove Windows long-path prefix if present
    if Result.StartsWith('\\?\') then
      Delete(Result, 1, 4);

  finally
    CloseHandle(FileHandle);
  end;
  {$ENDIF}

  {$IF Defined(LINUX)}
  var Utf8LinkName: UTF8String := UTF8Encode(ALinkName);
  var Buffer: array[0..Pred(MaxSupportedPathLen)] of AnsiChar;
  var Len: ssize_t := readlink(
    PAnsiChar(Utf8LinkName),
    Buffer,
    SizeOf(Buffer) - 1
  );
  if Len = -1 then
    RaiseSymlinkParseError(ALinkName);
  // readlink doesn't zero terminate the string placed in buffer, so we must
  Buffer[Len] := #0;
  Result := UTF8ToString(UTF8String(Buffer));
  {$ENDIF}
end;

end.

